[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = 'cs'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'msbuild server/OmniSharp.sln'
	else
		let cmd = 'xbuild server/OmniSharp.sln'
	endif
	let g:dein#plugin.build = cmd
'''
